source 'https://rubygems.org'
gem 'rails', '4.1.2'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'monban'
gem 'monban-generators'
gem 'bourbon'
gem 'neat'
gem 'bitters'
gem 'paperclip', '~> 4.1'
gem 'mysql2', '~> 0.3.13'
gem 'thinking-sphinx', '~> 3.1.1'
gem 'rails_12factor', group: :production
gem 'kaminari'
gem 'gretel'
gem 'gibbon', '~> 1.1.3'
gem 'letter_opener', group: :development
